# QLNet Appveyor builds

# Configuration for "master" branch
# build in Release mode and deploy to Nuget and GitHub
-
  branches:
    only:
      - master
  version: 1.13.0
  configuration: Release
  platform: Any CPU
  image: Visual Studio 2022
  test: off
  skip_tags: true
  pull_requests:
    do_not_increment_build_number: true  
  nuget:
    disable_publish_on_pr: true
  build_script:
   - cmd:  dotnet build -c Release
  after_build:
    - cmd: dotnet pack src/qlnet/qlnet.csproj -c Release -o ./
  artifacts:
    - path: src\QLNet\bin\Release\net8.0\QLNet.dll
      name: Windows
    - path: .\*.nupkg
      name: ng
  deploy:
  - provider: GitHub
    tag: QLNet-v1.13.0
    release: QLNet Version 1.13.0
    description: QLNet 1.13.0
    auth_token:
      secure: 4cCBgQRwNh1N6VbvMJTCUDVyo4z4acn5q6z4PXSgW5wOA0M2e6alGZms4fBx5Vw+6W8FieXgzRUvUfxmJ/xAnjxJZAFMeqI0mifvwMxjW9JAVC3EcFnV4NNZX/QoQRk6
    artifact: src\QLNet\bin\Release\net8.0\QLNet.dll
    draft: false
    force_update: false
  - provider: NuGet
    api_key:
      secure: LfB0vicMVT0ZgtDL1NtPmI+zC4he3BfQcO+2BlaN/0qlEnH4F6cz8K5QrM78OnoZ
    skip_symbols: true
    artifact: ng

# Configuration for "develop" branch
# build in Release mode, run tests , deploy to Sonar
-
  branches:
    only:
      - develop
  version: 1.13.1-preview.{build}
  configuration: Release
  platform: Any CPU
  image: Visual Studio 2022
  skip_tags: true
  clone_folder: c:\projects\qlnet_develop
  pull_requests:
    do_not_increment_build_number: true
  nuget:
    disable_publish_on_pr: true
  init:
    - cmd: set JAVA_HOME=C:\Program Files\Java\jdk17
  before_build:
  - cmd: "dotnet tool install --global dotnet-sonarscanner"
  - cmd: "SET runner_args=\"\""
  - cmd: "if \"%APPVEYOR_PULL_REQUEST_NUMBER%\"==\"\" SET runner_args=%sonar_commit_new%"
  - cmd: "if not \"%APPVEYOR_PULL_REQUEST_NUMBER%\"==\"\" SET runner_args=%sonar_pr_new%"
  - cmd: "dotnet sonarscanner begin %runner_args%"
  build_script:
   - cmd:  dotnet build -c Release
  artifacts:
    - path: .\*.nupkg
      name: ng
  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '{version}'
    assembly_version: '{version}'
    file_version: '{version}'
    informational_version: '{version}'
  test_script:
    - cmd: dotnet test -v=normal --no-build -p:Configuration=Release --collect "XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
  after_test:
    - cmd: "dotnet sonarscanner end /d:\"sonar.login=%sonar_token_new%\""  
    - cmd: dotnet pack src/qlnet/qlnet.csproj -c Release -o ./
  deploy:
    - provider: NuGet
      api_key:
        secure: LfB0vicMVT0ZgtDL1NtPmI+zC4he3BfQcO+2BlaN/0qlEnH4F6cz8K5QrM78OnoZ
      skip_symbols: false
      artifact: ng

# Configuration for "feature/*" branch
# build in Release mode, run tests , deploy to Nuget
-
  branches:
    only:
      - /feature/
  version: 1.13.1-{build}
  configuration: Release
  platform: Any CPU
  image: Visual Studio 2022
  skip_tags: true
  clone_folder: c:\projects\qlnet_feature
  init:
    - cmd: set JAVA_HOME=C:\Program Files\Java\jdk11
    - cmd: "set branch=%APPVEYOR_REPO_BRANCH%\necho branch:%branch%\nset gitVersion=%branch:/=.%\necho gitversion:%gitVersion%\nset newVersion=%gitVersion%.%APPVEYOR_BUILD_NUMBER%\necho %newVersion%"
    - cmd: appveyor UpdateBuild -Version "1.12.1-%newVersion%"
  before_build:
    - cmd: dotnet restore qlnet.sln
  build_script:
   - cmd:  dotnet build -c Release
  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '{version}'
    assembly_version: '{version}'
    file_version: '{version}'
    informational_version: '{version}'
  pull_requests:
    do_not_increment_build_number: true
  nuget:
    disable_publish_on_pr: true
  test_script:
    - cmd:  dotnet test -v=normal --no-build -p:Configuration=Release   

